version = 0.1
[default.deploy.parameters]
stack_name = "sns-to-sqs-lambda"
resolve_s3 = true
s3_prefix = "sns-to-sqs-lambda"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SNSTopicArnSecret=\"ses-to-sns-agent-topic\" SQSQueueNameSecret=\"unified-queue\""
image_repositories = []
